#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
rm -rf $HOME/.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Vim
rm -rf $HOME/.vim
ln -sf $DOTFILES/vim/.vim $HOME/.vim

rm -rf $HOME/.vimrc
ln -sf $DOTFILES/vim/vimrc $HOME/.vimrc

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
